export const ADD_PERMIT = 'ADD_PERMIT'
export const ADD_APPLICANT = 'ADD_APPLICANT'
export const ADD_CONTRACTOR = 'ADD_CONTRACTOR'
export const ADD_OWNER = 'ADD_OWNER'

export const DELETE_PERMIT = 'DELETE_PERMIT'
export const DELETE_APPLICANT = 'DELETE_APPLICANT'
export const DELETE_CONTRACTOR = 'DELETE_CONTRACTOR'
export const DELETE_OWNER = 'DELETE_OWNER'

export const EDIT_PERMIT = 'EDIT_PERMIT'
export const EDIT_APPLICANT = 'EDIT_APPLICANT'
export const EDIT_CONTRACTOR = 'EDIT_CONTRACTOR'
export const EDIT_OWNER = 'EDIT_OWNER'

export const CHANGE_SECTION = 'CHANGE_SECTION'
export const CHANGE_EXPANDED_ITEM = 'CHANGE_EXPANDED_ITEM'
